uploads = []
outputs = []

[[generated]]
id = "qrWicg-zLBaNA8TpJyMEn"
uri = "file://artifacts/grownergy/src/assets/images/hero-solar.png"
type = "image"
title = "Solar panels at sunset"

[[generated]]
id = "UhhO_1h_YrbqBY-ZefOrf"
uri = "file://artifacts/grownergy/src/assets/images/about-solar.png"
type = "image"
title = "Sustainable home with solar"

[[generated]]
id = "-7atvFgQd9fSEdeLh52fB"
uri = "file://artifacts/grownergy/src/assets/images/project-1.png"
type = "image"
title = "Commercial solar installation"

[[generated]]
id = "ZPYNyoFrXKpYv_Wu7mwr9"
uri = "file://artifacts/grownergy/src/assets/images/project-2.png"
type = "image"
title = "Residential solar roof"

[[generated]]
id = "2vMCKe3tGJ_t6BS0eSJlz"
uri = "file://artifacts/grownergy/src/assets/images/project-3.png"
type = "image"
title = "Solar parking canopy"
