kind = "web"
previewPath = "/"
title = "Grownergy"
version = "1.0.0"
id = "artifacts/grownergy"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23687

[services.development]
run = "pnpm --filter @workspace/grownergy run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/grownergy", "run", "build" ]
publicDir = "artifacts/grownergy/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23687"
BASE_PATH = "/"
